engines:
    duplication:
        enabled: true
        config:
            languages:
                - python
    pep8:
        enabled: false
    fixme:
        enabled: true
    radon:
        enabled: true

ratings:
    paths:
        - "**/*.py"

exclude_paths:
    - "versioneer.py"
    - "deeplook/_version.py"
    - "doc/**/*"
    - "ci/*"
    - "deeplook/tests/data/*"
