name: deeplook
channels:
    - conda-forge
dependencies:
    - python=2.7
    - pip
    - numpy
    - future
    - dask
    - fatiando
    - matplotlib
    - pytest
    - pytest-cov
    - coverage
    - flake8
    - pylint
    - sphinx
    - sphinx_rtd_theme
    - nbsphinx
    - numpydoc
    - twine
